project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    toc: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

<% if(editor){ %>editor: <%= editor %><% } %>
